<a href="https://colab.research.google.com/github/feli23/Test/blob/main/Intorduction_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch

#**List**

In [ ]:
my_list = [[1,2,3,4,5],[6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **Numpy Arrays**

In [ ]:
np1 = np.random.rand(3, 4)
np1

array([[0.26303475, 0.80777236, 0.53649034, 0.49377537],
       [0.25433122, 0.85062699, 0.30037548, 0.42085488],
       [0.99089862, 0.99650127, 0.02458881, 0.73380029]])

In [ ]:
np2 = np.random.rand(2, 3, 4)
np2

array([[[0.82294057, 0.04354833, 0.92745209, 0.37384902],
        [0.21707081, 0.64927197, 0.49033966, 0.50589332],
        [0.09586729, 0.9102535 , 0.26903831, 0.39940585]],

       [[0.50843653, 0.44320889, 0.61413469, 0.13659857],
        [0.59184561, 0.25976509, 0.39759114, 0.18490952],
        [0.01035007, 0.26403504, 0.73106423, 0.16568322]]])

# **Tensors**

In [ ]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-2.3098e+00, -3.2690e-01,  7.0244e-01,  1.1887e+00],
        [ 2.7588e+00,  2.6280e+00, -1.7837e+00, -4.5719e-01],
        [-2.9529e-02, -1.4139e-01,  1.5168e-03,  1.0162e+00]])

In [ ]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## **Create Tensors out of numpy arrays**

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2630, 0.8078, 0.5365, 0.4938],
        [0.2543, 0.8506, 0.3004, 0.4209],
        [0.9909, 0.9965, 0.0246, 0.7338]], dtype=torch.float64)

In [ ]:
my_tensor2 = torch.tensor(np2)
my_tensor2

tensor([[[0.8229, 0.0435, 0.9275, 0.3738],
         [0.2171, 0.6493, 0.4903, 0.5059],
         [0.0959, 0.9103, 0.2690, 0.3994]],

        [[0.5084, 0.4432, 0.6141, 0.1366],
         [0.5918, 0.2598, 0.3976, 0.1849],
         [0.0104, 0.2640, 0.7311, 0.1657]]], dtype=torch.float64)

## **Tensor Operations**

In [15]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### **Reshape and View**

In [16]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**Reshape if you don't know the number of items using -1**

In [26]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
my_torch2 = my_torch2.reshape(-1, 3)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [30]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Differences in Reshape and view in Stackoverflow: https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch

**Reshape and view will update**

In [33]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [36]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

###**Slices**

In [37]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Grab specific item**

In [38]:
my_torch7[7]

tensor(7)

**Grab a slice**

In [39]:
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [43]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [44]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])